services:
  - type: web
    name: telegram-downloader-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT & python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_URL
        sync: false